In [23]:
import sys
import numpy as np

print('import numpy as np <- fundemental package for scientific computing with python')
print('we"re going to use it to create and manipulate with arrays')
print('Numpy: {}'.format(np.__version__))

import numpy as np <- fundemental package for scientific computing with python
we"re going to use it to create and manipulate with arrays
Numpy: 1.19.5


In [24]:
### SCALARS 
x=6
print('SCALARS')
print('Defining a scalar: x=6 and you can use print(x)')
print(x)

SCALARS
Defining a scalar: x=6 and you can use print(x)
6


In [25]:
### VECTOR
print('VECTORS')
x=np.array((1,2,3))		# CODE
print('Defining a one dimensional vector: x=np.array((1,2,3))')
dimensions=x.shape		# CODE
print('Vector Dimensions: {}'.format(x.shape))
size=x.size
print('Vector size: {}'.format(x.size))
print(x)
print([1, 2, 3])

VECTORS
Defining a one dimensional vector: x=np.array((1,2,3))
Vector Dimensions: (3,)
Vector size: 3
[1 2 3]
[1, 2, 3]


In [26]:
print('The unit vector - vector with unit form')
print('A unit vector can be obtained by normalizing any vector')
print('Vector normalization is the process of dividing a vectorby its magnitude, which produces a unit vector')
x=[1,1,1,1]
print ('vector x -> ' , x)
print('example of normalization -> x/((1^2+1^2+1^2+1^2)^1/2)=x/(4^1/2)=1/2')
x=[1/2,1/2,1/2,1/2]
print('Unit vector-> ' ,x)
print('normalization improve the perfomance of ML algorithms')
print('We use euclidian norm - > between (0,1)')
print('Normalization is used between the layers of the NN')

The unit vector - vector with unit form
A unit vector can be obtained by normalizing any vector
Vector normalization is the process of dividing a vectorby its magnitude, which produces a unit vector
vector x ->  [1, 1, 1, 1]
example of normalization -> x/((1^2+1^2+1^2+1^2)^1/2)=x/(4^1/2)=1/2
Unit vector->  [0.5, 0.5, 0.5, 0.5]
normalization improve the perfomance of ML algorithms
We use euclidian norm - > between (0,1)
Normalization is used between the layers of the NN


In [27]:
### MATRICE
print('MATRICES')
X = np.matrix([[2,4,6],[3,5,7],[8,5,3]])
print('Defining a matrix X = np.matrix([[2,4,6],[3,5,7],[8,5,3]])')
print(X)
print('Matrix dimensions: {}'.format(X.shape))
print('Matrix size: {}'.format(X.size))
# again you can save these parameters like we did with vectors

MATRICES
Defining a matrix X = np.matrix([[2,4,6],[3,5,7],[8,5,3]])
[[2 4 6]
 [3 5 7]
 [8 5 3]]
Matrix dimensions: (3, 3)
Matrix size: 9


In [28]:
print('MATRIX OPERATIONS')
Y = np.matrix([[10,11,12],[13,14,15],[16,17,18]])
print('Define a matrix Y = np.matrix([[10,11,12],[13,14,15],[16,17,18]]')
print('Matrices:')
print(X, '\n''\n', Y)
print('Addition: X+Y')
print(X+Y)
 
print('Addition: X-Y')
print(X-Y)

print('Addition: X*Y')
print(X*Y)

print('Addition: X/Y')
print(X/Y)

MATRIX OPERATIONS
Define a matrix Y = np.matrix([[10,11,12],[13,14,15],[16,17,18]]
Matrices:
[[2 4 6]
 [3 5 7]
 [8 5 3]] 

 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Addition: X+Y
[[12 15 18]
 [16 19 22]
 [24 22 21]]
Addition: X-Y
[[ -8  -7  -6]
 [-10  -9  -8]
 [ -8 -12 -15]]
Addition: X*Y
[[168 180 192]
 [207 222 237]
 [193 209 225]]
Addition: X/Y
[[0.2        0.36363636 0.5       ]
 [0.23076923 0.35714286 0.46666667]
 [0.5        0.29411765 0.16666667]]


In [29]:
print('Matrix transponse')
A=np.array(range(9))
print('A=np.array(range(9))')
print(A)
print('A=A.reshape(3,3)')
A=A.reshape(3,3)
print(A)
print('B=A.T')
B=A.T
print(B)
print('transponse of transponse = ORIGINAL matrix')

Matrix transponse
A=np.array(range(9))
[0 1 2 3 4 5 6 7 8]
A=A.reshape(3,3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
B=A.T
[[0 3 6]
 [1 4 7]
 [2 5 8]]
transponse of transponse = ORIGINAL matrix


In [30]:
print('Some matrices and vectors occure more commonly than others or are particulary useful in ML')
print('Diagonal Matrices - > Dij = 0 for all i!=j ')
print('All the elements equals to 0 except allong the main diagonal')
A=np.matrix([[1,0,0],[0,2,0],[0,0,3]])
print(A)

Some matrices and vectors occure more commonly than others or are particulary useful in ML
Diagonal Matrices - > Dij = 0 for all i!=j 
All the elements equals to 0 except allong the main diagonal
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [31]:
print('Symetric matrices - across the main diagonal')
print('A symmetric matrix is any matrix that is equal to its transpose')
A=np.matrix([[1,2,3],[2,3,4],[3,4,5]])
print(A)
print('For example distance measurement matrix')

Symetric matrices - across the main diagonal
A symmetric matrix is any matrix that is equal to its transpose
[[1 2 3]
 [2 3 4]
 [3 4 5]]
For example distance measurement matrix


In [32]:
print('Calculate the determinant of matrix X // np.linalg.det(X) // : ')
print(np.linalg.det(X))

Calculate the determinant of matrix X // np.linalg.det(X) // : 
-2.000000000000001


In [35]:
print('Defining a matrix of a given dimension')
print('x=np.ones(5,5) or zeros(3,3)')
x=np.ones((5,5))
y=np.zeros((3,3))
z=np.random.random((3, 3))
print(x,'\n', '\n',y)
z

Defining a matrix of a given dimension
x=np.ones(5,5) or zeros(3,3)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 
 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[0.8768323 , 0.97603423, 0.60523243],
       [0.59970727, 0.22619036, 0.59359287],
       [0.02742738, 0.81551558, 0.78558873]])

In [36]:
print('TENSORS')
x=np.ones((3,3,3))
print('3 dimensional tensor x=np.ones((3,3,3))')
print(x)
print('You can add 4-5-6... dimesional tensors')
print('It gets harder and harder to visualize (2-D screen)')
print('Tensor dimensions: {}'.format(x.shape))
print('Tensor size: {}'.format(x.size))
# Again you can save this like x=x.size or x=x.shape
print('With adding dimensions -> we have exponential increase of number of parameters')

TENSORS
3 dimensional tensor x=np.ones((3,3,3))
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
You can add 4-5-6... dimesional tensors
It gets harder and harder to visualize (2-D screen)
Tensor dimensions: (3, 3, 3)
Tensor size: 27
With adding dimensions -> we have exponential increase of number of parameters


In [40]:
# INDEXING
A=np.ones((5,5), dtype=np.int)
print('A=np.ones((5,5), dtype=np.int)-> data type integers - default FLOAT')
print(A)
print('Idexing starts at 0 -> first element is A[0,0]')
print('print(A[:,0]) -> prints first column or you can assign values')
print('print(A[:,:])')
A[::2, 2]

A=np.ones((5,5), dtype=np.int)-> data type integers - default FLOAT
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Idexing starts at 0 -> first element is A[0,0]
print(A[:,0]) -> prints first column or you can assign values
print(A[:,:])


array([1, 1, 1])

In [44]:
print('Higher dimension -> A=np.ones((5,5,5), dtype=np.int)')
A=np.ones((5,5,5))
print('Assig first row a new value -> A[:,0,0]=6')
A[:,0,0]=np.random.random(5)
print(A)

Higher dimension -> A=np.ones((5,5,5), dtype=np.int)
Assig first row a new value -> A[:,0,0]=6
[[[0.71665746 1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[0.32890103 1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[0.30905622 1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[0.03782191 

In [45]:
# tensors
print('A=np.ones((3,3,3,3,3,3,3,3,3,3)) - 10d tensor')
A=np.ones((3,3,3,3,3,3,3,3,3,3))

print('Again A.shape for printing dimensions ->' ,len(A.shape))
print('A.size print number of elements - exponential growth ->', A.size)
print('TENSORS- > AI')

A=np.ones((3,3,3,3,3,3,3,3,3,3)) - 10d tensor
Again A.shape for printing dimensions -> 10
A.size print number of elements - exponential growth -> 59049
TENSORS- > AI


In [46]:
import numpy as np
nx, ny = (100, 100)

# nx points in  0-10 range
x = np.linspace(0, 10, nx)
y = np.linspace(0, 10, ny)

# combine
xv, yv = np.meshgrid(x,y)


# define function to plot
def f(x,y):
    return x * (y**2)

z = f(xv, yv)
print(z)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.03061015e-03 2.06122030e-03 ... 9.99691848e-02
  1.00999795e-01 1.02030405e-01]
 [0.00000000e+00 4.12244061e-03 8.24488122e-03 ... 3.99876739e-01
  4.03999180e-01 4.08121620e-01]
 ...
 [0.00000000e+00 9.69701092e+00 1.93940218e+01 ... 9.40610059e+02
  9.50307070e+02 9.60004081e+02]
 [0.00000000e+00 9.89797990e+00 1.97959598e+01 ... 9.60104050e+02
  9.70002030e+02 9.79900010e+02]
 [0.00000000e+00 1.01010101e+01 2.02020202e+01 ... 9.79797980e+02
  9.89898990e+02 1.00000000e+03]]


In [48]:
# defining our function
# The derivate is just how much the function is increasing or decreasing at a certain point
def f(x):
    return x**2

def derivative(x):
    # h is the change in x. It used to be called delta(x)
    h = 1./1000.
    rise = f(x + h)- f(x)
    run = h
    slope = rise / run
    return slope

In [49]:
print(derivative(1))
print(derivative(2))
print(derivative(3))

2.0009999999996975
4.000999999999699
6.000999999999479


In [50]:
# The definite integral is the area under a curve. 
# It is approximated by adding up a tons of rectangles/
# Height of rectangle is f(x)
# The more rectangles - > The better approximation
def integral(startingx, endingx, numberofRectangles):
    width = (float(endingx) - float(startingx))/numberofRectangles
    # This will be the running sum of the areas
    runningSum=0
    for i in range(numberofRectangles):
        # each rectangle is 1 width after the previous one
        height = f(startingx + i*width)
        area = height * width
        # updating the running sum of the areas
        runningSum += area
    return runningSum

In [51]:
integral(0,1,100000)

0.33332833334999745